### PR TITLE
Improve project description in ide-projects.md

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@codenvy.com>

Improve project description in ide-projects.md

### CODE REVIEW

**Comment by slemeur** [comment]
Here, what's important to mention:
- User is able to manage projects by using the dashboard or the IDE
- Projects can be deleted from a workspace, only when the workspace is running.

**Comment by slemeur** [comment]
You can create a new sub-section in the page for that.

**Comment by olexii4** [comment]
selection_041

**Comment by JamesDrummond** [comment]
I committed some revisions. I included some todo tasks. Needs some more work. Add images and try to walk through all project menu items and right click menu items sections. Now that I have made revisions to this page I can see how much information it has lacked for users.

**Comment by bmicklea** [comment]
@JamesDrummond - what's the status of this - are you still making changes?  Or should this be approved and merged?

**Comment by JamesDrummond** [comment]
No this needs to be improved but I didn't assign myself. I can put on agenda.

**Pull request merged**
