### PR TITLE
Add Angular2 tutorial

### PR DESCRIPTION
**Pull request by eivantsov**
A simple Angular 2 tutorial

### CODE REVIEW

**Comment by bmicklea** [comment]
@JamesDrummond - how do we work around that?

**Comment by JamesDrummond** [comment]
&#123;&#123;title&#125;&#125; &#123;&#123;newtitle&#125;&#125;

**Comment by eivantsov** [comment]
@JamesDrummond can you push it yourself please since I am not sure I get it right.

**Comment by JamesDrummond** [comment]
@eivantsov Looks like my solutions doesn't work inside of ```code sections```. I figured out a different way to accomplish it which I pushed.

**Comment by eivantsov** [comment]
OK, either way works for me :)

**Pull request merged**
