### PR TITLE
docs for basic assembly

### PR DESCRIPTION
**Pull request by skabashnyuk**
Related to 
- https://github.com/eclipse/che/pull/4578
- https://github.com/codenvy/codenvy/pull/2060

### CODE REVIEW

**Comment by slemeur** [comment]
Few points:
1- I don't see how these pages will be enabled and accessible from docs navigation menu.
2- We don't put the codenvy's docs on the Che docs. There is another repository for codenvy docs: https://github.com/codenvy/docs

If you have pages of che docs that you want to display in codenvy docs you have few examples, last recent one are the docs on factories (https://github.com/eclipse/che-docs/pull/194)

**Comment by skabashnyuk** [comment]
1. I have no idea what is it and how to do that.
2. https://github.com/codenvy/docs/pull/110

**Comment by bmicklea** [comment]
I think the documentation snippet you've added would go on the [assembly lifecycle page](https://eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html), right?

If so, where do you think it belongs?

**Comment by skabashnyuk** [comment]
I think https://eclipse.org/che/docs/assemblies/assembly-lifecycle/index.html#customizing

**Comment by bmicklea** [comment]
Closing without merging as docs for Che and Codenvy were added to Che PR: https://github.com/eclipse/che-docs/pull/202

**Pull request closed without merging**
